export default function reducer(state={
    s1_button 			 : "Baca Lebih Lanjut",
    s2_title  			 : "Penyedia Solusi Energi Anda",
    s2_content   		 : "Menyediakan solusi energi skala besar, menengah, dan kecil dengan mempertimbangkan kontinuitas suplai dan kehandalan sistem melalui pengelolaan dan penggunaan energi secara ekonomis dan ramah lingkungan.",
    s3_title  			 : "Tata Nilai Perusahaan",
    s3_1   		 		   : "Layanan Prima",
    s3_1_content 		 : "Berorientasi pada kepentingan pelanggan dan berkomitmen untuk memberikan pelayanan terbaik pada pelanggan",
    s3_2 				     : "Bekerja Sama",
    s3_2_content 		 : "Menjalin kerja sama yang padu dengan semua pihak demi tumbuh kembangnya usaha masing-masing pihak",
    s3_3 				     : "Kompetitif",
    s3_3_content 		 : "Mampu berkompetisi, mendorong pertumbuhan, membangun budaya sadar biaya dan mengambil keputusan berdasarkan prinsip-prinsip bisnis yang sehat",
    s3_4 				     : "Berkemampuan",
    s3_4_content 		 : "Dikelola oleh pemimpin dan pekerja yang profesional dan berintegritas serta berkomitmen dalam pengembangan dengan perbaikan berkesinambungan demi tercapainya kepuasan para stakeholder",
  	s4_title 			   : "Apa yang Kami Kerjakan",
  	s4_1 				     : "Layanan Konsultasi",
  	s4_2 				     : "Solusi dan Analisis Konversi",
  	s4_3 				     : "Analisis Ekonomi",
  	s4_4 				     : "Pemasangan Sistem dan Infrastruktur",
  	s4_5 				     : "Suplai, Operasi, dan Perawatan",
  	s5_title 			   : "Bisnis Kami",
  	s5_1 				     : "Gas Alam",
  	s5_1_content_1	 : "Suplai dan Distribusi CNG",
  	s5_1_content_2 	 : "Desain, Frabrikasi, dan Pemasangan PRS",
  	s5_1_content_3 	 : "Operasi, Perawatan, dan Perbaikan",
  	s5_1_content_4 	 : "EPC untuk Piping, Mekanikal, dan Instrument Elektrikal",
  	s5_2 				     : "Konsultasi Energi",
  	s5_2_content_1 	 : "Kehandalan Sistem",
  	s5_2_content_2 	 : "Efisiensi Energi",
  	s5_2_content_3 	 : "Alternatif Energi",
  	s5_3 				     : "Kelistrikan",
  	s5_3_content_1 	 : "Load Sharing dan Load Shedding",
  	s5_3_content_2 	 : "Penilaian Aset dan Layanan Shutdown Terencana",
  	s5_3_content_3 	 : "Substation HV/MV/LV",
  	s5_3_content_4 	 : "Generator dan Panel Kontrol",
  	s5_3_content_5 	 : "Retrofit",
  	s5_3_content_6 	 : "Refurbishment",
  	s5_button 			 : "Portofolio Kami",
    s6_title         : "Pelanggan Kami",
  }, action) {
	switch (action.type) {
		case 'CHANGE_LANGUAGE_IND_TO_ENG' : {
			return  {
				...state,
				  s1_button        : "See More",
          s2_title         : "YOUR ENERGY SOLUTION PROVIDER",
          s2_content       : "We provide small, medium, and large scale energy solution by considering supply continuity and system reliability through energy management and utilization in economical and environment-friendly manner.",
          s3_title         : "COMPANY VALUES",
          s3_1             : "EXCELLENT SERVICE",
          s3_1_content     : "We are customer benefit oriented and committed to deliver the best service to our customers",
          s3_2             : "COOPERATIVE",
          s3_2_content     : "Building integrated cooperation among the stakeholders for the sake of each stakeholders' growth",
          s3_3             : "COMPETITIVE",
          s3_3_content     : "Competitive, empower growth, building cost-oriented culture, and make decision based on healthy business principles",
          s3_4             : "COMPETENT",
          s3_4_content     : "Managed by professional leaders and employees with integrity and commitment in sustainable development for satisfaction of stakeholders",
          s4_title         : "WHAT WE DO",
          s4_1             : "Consulting Services",
          s4_2             : "Solution and Conversion Analysis",
          s4_3             : "Payback and Economic Analysis",
          s4_4             : "System and Infrastructure Setup",
          s4_5             : "Supply, Operation, and Maintenance",
          s5_title         : "OUR BUSINESS LINE",
          s5_1             : "Natural Gas",
          s5_1_content_1   : "CNG Supply and Distribution",
          s5_1_content_2   : "PRS Design, Production, and Installation",
          s5_1_content_3   : "Operation, Maintenance, and Refurbishment",
          s5_1_content_4   : "EPC for Piping, Mechanical, and Electrical Instrumentation",
          s5_2             : "Energy Consulting",
          s5_2_content_1   : "System Reliability",
          s5_2_content_2   : "Energy Efficiency",
          s5_2_content_3   : "Energy Alternatives",
          s5_3             : "Electricity",
          s5_3_content_1   : "Load Sharing and Load Shedding System",
          s5_3_content_2   : "Asset Assessment and Planned Shutdown Services",
          s5_3_content_3   : "HV/MV/LV Substation",
          s5_3_content_4   : "Generator and Control Panel",
          s5_3_content_5   : "Retrofit",
          s5_3_content_6   : "Refurbishment",
          s5_button        : "Our Portfolio",
          s6_title         : "Our Customers",
			}
		}

		case 'CHANGE_LANGUAGE_ENG_TO_IND' : {
			return  {
				...state,
          s1_button        : "Baca Lebih Lanjut",
          s2_title         : "Penyedia Solusi Energi Anda",
          s2_content       : "Menyediakan solusi energi skala besar, menengah, dan kecil dengan mempertimbangkan kontinuitas suplai dan kehandalan sistem dengan mengelola dan menggunakan energi secara ekonomis dan ramah lingkungan.",
          s3_title         : "Tata Nilai Perusahaan",
          s3_1             : "Layanan Prima",
          s3_1_content     : "Berorientasi pada kepentingan pelanggan dan berkomitmen untuk memberikan pelayanan terbaik pada pelanggan",
          s3_2             : "Bekerja Sama",
          s3_2_content     : "Menjalin kerja sama yang padu dengan semua pihak demi tumbuh kembangnya usaha masing-masing pihak",
          s3_3             : "Kompetitif",
          s3_3_content     : "Mampu berkompetisi, mendorong pertumbuhan, membangun budaya sadar biaya dan mengambil keputusan berdasarkan prinsip-prinsip bisnis yang sehat",
          s3_4             : "Berkemampuan",
          s3_4_content     : "Dikelola oleh pemimpin dan pekerja yang profesional dan berintegritas serta berkomitmen dalam pengembangan dengan perbaikan berkesinambungan demi tercapainya kepuasan para stakeholder",
          s4_title         : "Apa yang Kami Kerjakan",
          s4_1             : "Layanan Konsultasi",
          s4_2             : "Solusi dan Analisis Konversi",
          s4_3             : "Analisis Ekonomi",
          s4_4             : "Pemasangan Sistem dan Infrastruktur",
          s4_5             : "Suplai, Operasi, dan Perawatan",
          s5_title         : "Bisnis Kami",
          s5_1             : "Gas Alam",
          s5_1_content_1   : "Suplai dan Distribusi CNG",
          s5_1_content_2   : "Desain, Frabrikasi, dan Pemasangan PRS",
          s5_1_content_3   : "Operasi, Perawatan, dan Perbaikan",
          s5_1_content_4   : "EPC untuk Piping, Mekanikal, dan Instrument Elektrikal",
          s5_2             : "Konsultasi Energi",
          s5_2_content_1   : "Kehandalan Sistem",
          s5_2_content_2   : "Efisiensi Energi",
          s5_2_content_3   : "Alternatif Energi",
          s5_3             : "Kelistrikan",
          s5_3_content_1   : "Load Sharing dan Sistem Load Shedding",
          s5_3_content_2   : "Penilaian Aset dan Layanan Shutdown Terencana",
          s5_3_content_3   : "Substation HV/MV/LV",
          s5_3_content_4   : "Generator dan Panel Kontrol",
          s5_3_content_5   : "Retrofit",
          s5_3_content_6   : "Refurbishment",
          s5_button        : "Portofolio Kami",
          s6_title         : "Pelanggan Kami",
			}
		}
	}

	return state;
}